#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::{Account, Provider};
    use chrono::Utc;
    use std::path::PathBuf;

    fn account(provider: Provider, alias: &str, dir: &str, use_default_dir: bool) -> Account {
        Account {
            id: alias.into(),
            provider,
            label: alias.into(),
            config_dir: PathBuf::from(dir),
            use_default_dir,
            pinned: false,
            alias_name: alias.into(),
            created_at: Utc::now(),
        }
    }

    #[test]
    fn renders_sh_aliases() {
        let out = render_sh(&[
            account(Provider::Claude, "claude-personal", "/Users/me/.claude-personal", false),
            account(Provider::Codex, "codex-main", "/Users/me/.codex", true),
        ]);
        assert!(out.starts_with(HEADER));
        assert!(out.contains("alias claude-personal='CLAUDE_CONFIG_DIR=\"/Users/me/.claude-personal\" claude'\n"));
        assert!(out.contains("alias codex-main='env -u CODEX_HOME codex'\n"));
    }

    #[test]
    fn escapes_quotes_in_sh_paths() {
        let out = render_sh(&[account(Provider::Claude, "claude-x", "/Users/o'neil/.claude-x", false)]);
        assert!(out.contains(r#"alias claude-x='CLAUDE_CONFIG_DIR="/Users/o'\''neil/.claude-x" claude'"#));
    }

    #[test]
    fn renders_powershell_functions_that_restore_env() {
        let out = render_ps1(&[account(Provider::Claude, "claude-work", r"C:\Users\me\.claude-work", false)]);
        assert!(out.contains("function claude-work {"));
        assert!(out.contains(r"$env:CLAUDE_CONFIG_DIR = 'C:\Users\me\.claude-work'"));
        assert!(out.contains("try { claude @args } finally {"));
        let default = render_ps1(&[account(Provider::Codex, "codex-main", r"C:\Users\me\.codex", true)]);
        assert!(default.contains("Remove-Item Env:CODEX_HOME -ErrorAction SilentlyContinue\n  try { codex @args }"));
    }

    #[test]
    fn install_block_is_idempotent_and_removable() {
        let block = sh_source_block(Path::new("/cfg/aliases.sh"));
        let original = "export FOO=1\n";
        let once = install_block(original, &block);
        let twice = install_block(&once, &block);
        assert_eq!(once, twice);
        assert!(once.contains(BLOCK_START) && once.contains("/cfg/aliases.sh"));
        assert_eq!(remove_block(&once), original);
        assert_eq!(install_block("", &block), block);
    }

    #[test]
    fn remove_block_leaves_unmarked_content_alone() {
        assert_eq!(remove_block("a\nb\n"), "a\nb\n");
    }
}

use crate::cli::locator::ShellEnv;
use crate::model::Account;
use crate::state::AppPaths;
use std::fs;
use std::io;
use std::path::{Path, PathBuf};

pub const HEADER: &str = "# Generated by Usage Monitor. Changes are overwritten.";
pub const BLOCK_START: &str = "# >>> usage-monitor aliases >>>";
pub const BLOCK_END: &str = "# <<< usage-monitor aliases <<<";

fn sh_single_quote(s: &str) -> String {
    format!("'{}'", s.replace('\'', "'\\''"))
}

fn ps_single_quote(s: &str) -> String {
    format!("'{}'", s.replace('\'', "''"))
}

fn sh_double_quote_escape(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"").replace('$', "\\$").replace('`', "\\`")
}

fn sh_line(account: &Account) -> String {
    let var = account.provider.config_env_var();
    let cli = account.provider.cli_name();
    let body = if account.use_default_dir {
        format!("env -u {var} {cli}")
    } else {
        format!("{var}=\"{}\" {cli}", sh_double_quote_escape(&account.config_dir.to_string_lossy()))
    };
    format!("alias {}={}", account.alias_name, sh_single_quote(&body))
}

fn ps1_function(account: &Account) -> String {
    let var = account.provider.config_env_var();
    let cli = account.provider.cli_name();
    let apply = if account.use_default_dir {
        format!("Remove-Item Env:{var} -ErrorAction SilentlyContinue")
    } else {
        format!("$env:{var} = {}", ps_single_quote(&account.config_dir.to_string_lossy()))
    };
    format!(
        "function {name} {{\n  $prev = $env:{var}\n  {apply}\n  try {{ {cli} @args }} finally {{ if ($null -ne $prev) {{ $env:{var} = $prev }} else {{ Remove-Item Env:{var} -ErrorAction SilentlyContinue }} }}\n}}",
        name = account.alias_name
    )
}

pub fn render_sh(accounts: &[Account]) -> String {
    let mut out = format!("{HEADER}\n");
    for account in accounts {
        out.push_str(&sh_line(account));
        out.push('\n');
    }
    out
}

pub fn render_ps1(accounts: &[Account]) -> String {
    let mut out = format!("{HEADER}\n");
    for account in accounts {
        out.push_str(&ps1_function(account));
        out.push('\n');
    }
    out
}

/// The single alias for this OS, for the "copy alias" button.
pub fn alias_line(account: &Account) -> String {
    if cfg!(windows) { ps1_function(account) } else { sh_line(account) }
}

pub fn sh_source_block(aliases_sh: &Path) -> String {
    let p = sh_single_quote(&aliases_sh.to_string_lossy());
    format!("{BLOCK_START}\n[ -f {p} ] && . {p}\n{BLOCK_END}\n")
}

pub fn ps1_source_block(aliases_ps1: &Path) -> String {
    let p = ps_single_quote(&aliases_ps1.to_string_lossy());
    format!("{BLOCK_START}\nif (Test-Path {p}) {{ . {p} }}\n{BLOCK_END}\n")
}

pub fn install_block(content: &str, block: &str) -> String {
    let cleaned = remove_block(content);
    let mut out = cleaned.trim_end_matches('\n').to_string();
    if !out.is_empty() {
        out.push_str("\n\n");
    }
    out.push_str(block);
    out
}

pub fn remove_block(content: &str) -> String {
    let (Some(start), Some(end_at)) = (content.find(BLOCK_START), content.find(BLOCK_END)) else {
        return content.to_string();
    };
    if end_at < start {
        return content.to_string();
    }
    let mut end = end_at + BLOCK_END.len();
    if content[end..].starts_with('\n') {
        end += 1;
    }
    let before = content[..start].trim_end_matches('\n');
    let after = &content[end..];
    match (before.is_empty(), after.is_empty()) {
        (true, _) => after.to_string(),
        (false, true) => format!("{before}\n"),
        (false, false) => format!("{before}\n{after}"),
    }
}

pub fn write_alias_files(paths: &AppPaths, accounts: &[Account]) -> io::Result<()> {
    fs::create_dir_all(&paths.config_dir)?;
    fs::write(paths.aliases_sh(), render_sh(accounts))?;
    fs::write(paths.aliases_ps1(), render_ps1(accounts))
}

enum ProfileKind {
    Sh,
    Ps1,
}

fn profile_targets(paths: &AppPaths, shell: &ShellEnv) -> Vec<(PathBuf, ProfileKind)> {
    if cfg!(windows) {
        return powershell_profiles().into_iter().map(|p| (p, ProfileKind::Ps1)).collect();
    }
    let existing: Vec<(PathBuf, ProfileKind)> = [".zshrc", ".bashrc"]
        .iter()
        .map(|f| paths.home.join(f))
        .filter(|p| p.exists())
        .map(|p| (p, ProfileKind::Sh))
        .collect();
    if !existing.is_empty() {
        return existing;
    }
    let name = if shell.get("SHELL").is_some_and(|s| s.ends_with("zsh")) { ".zshrc" } else { ".bashrc" };
    vec![(paths.home.join(name), ProfileKind::Sh)]
}

#[cfg(windows)]
fn powershell_profiles() -> Vec<PathBuf> {
    use std::os::windows::process::CommandExt;
    ["pwsh", "powershell"]
        .iter()
        .filter_map(|exe| {
            std::process::Command::new(exe)
                .args(["-NoProfile", "-Command", "$PROFILE"])
                .creation_flags(0x0800_0000)
                .output()
                .ok()
        })
        .filter(|o| o.status.success())
        .map(|o| PathBuf::from(String::from_utf8_lossy(&o.stdout).trim()))
        .filter(|p| !p.as_os_str().is_empty())
        .collect()
}

#[cfg(not(windows))]
fn powershell_profiles() -> Vec<PathBuf> {
    Vec::new()
}

pub fn install(paths: &AppPaths, shell: &ShellEnv) -> io::Result<Vec<PathBuf>> {
    let mut done = Vec::new();
    for (target, kind) in profile_targets(paths, shell) {
        let block = match kind {
            ProfileKind::Sh => sh_source_block(&paths.aliases_sh()),
            ProfileKind::Ps1 => ps1_source_block(&paths.aliases_ps1()),
        };
        let current = fs::read_to_string(&target).unwrap_or_default();
        if let Some(parent) = target.parent() {
            fs::create_dir_all(parent)?;
        }
        fs::write(&target, install_block(&current, &block))?;
        done.push(target);
    }
    Ok(done)
}

pub fn uninstall(paths: &AppPaths, shell: &ShellEnv) -> io::Result<()> {
    for target in installed_targets(paths, shell) {
        let current = fs::read_to_string(&target)?;
        fs::write(&target, remove_block(&current))?;
    }
    Ok(())
}

pub fn installed_targets(paths: &AppPaths, shell: &ShellEnv) -> Vec<PathBuf> {
    profile_targets(paths, shell)
        .into_iter()
        .map(|(p, _)| p)
        .filter(|p| fs::read_to_string(p).is_ok_and(|c| c.contains(BLOCK_START)))
        .collect()
}
